apiVersion: apps/v1

kind: Deployment

metadata:

  name: pyapp-deployment

spec:

  replicas: 1

  selector:
     matchLabels:

       app: pyapp

  template:

    metadata:
        name: pypod
        labels:
          app: pyapp

    spec:

      containers:

      - name: pycontainer

        image: gcr.io/devops-374608/django-gunicorn:tagversion

        ports:

        - containerPort: 8000


---

apiVersion: v1
kind: Service
metadata:
  name: python-svc
spec:
  type: LoadBalancer
  selector:
    app: pyapp
  ports:
  - port: 80
    targetPort: 8000

